create database retails;

use retails;



select * from retail_cleaned;

select count(distinct(customer_id)) from retail_cleaned;
--Business Questions

--1. Which category generates the highest revenue ?

select category,round(sum(purchase_amount),2) as total_revenue from retail_cleaned group by category order by total_revenue desc;

--2. Are discounts actually increasing purchase value ?

select discount_applied,round(sum(purchase_amount),2) as total_amount, count(customer_id) as total_customers,
round(avg(purchase_amount),2)as average_amt from retail_cleaned group by discount_applied;

--3. What is the total revenue generated by male and female customers ?

select gender, count(customer_id) as total_count,round(sum(purchase_amount),2) as total_revenue from retail_cleaned group by gender;

--4. Which customers used the discount but still purchased more than average purchase amount ?

select customer_id, round(purchase_amount,2) as purchase_amount from retail_cleaned
where discount_applied='Yes' and purchase_amount>(Select avg(purchase_amount) from retail_cleaned);


-- 5. Which are top/bottom 5  products with highest average review rating ?

select * from retail_cleaned;

select top 5
item_purchased,round(avg(review_rating),2) as average_rating from retail_cleaned group by item_purchased order by avg(review_rating) desc;


select top 5
item_purchased,round(avg(review_rating),2) as average_rating from retail_cleaned group by item_purchased order by avg(review_rating);


--6.Average Purchase: Standard VS Express Shipping

select shipping_type,count(distinct(customer_id)) as total_customers, 
round(avg(purchase_amount),2) as average_purchase,
round(sum(purchase_amount),2) as total_revenue
from retail_cleaned group by shipping_type
order by total_revenue desc;

SELECT shipping_type, category,
       round(AVG(purchase_amount),2) AS avg_purchase
FROM retail_cleaned
GROUP BY shipping_type, category order by avg_purchase desc;

--7.	Do subscribed customers spend more ? 
--Compare average spend and total revenue between subscribers and non-subscribers.

select * from retail_cleaned;

select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_purchase,
round(sum(purchase_amount),2) as total_amount
from retail_cleaned group by subscription_status;

SELECT subscription_status, category,
       round(avg(purchase_amount),2) AS avg_purchase
FROM retail_cleaned
GROUP BY subscription_status, category;

SELECT subscription_status,
       round(AVG(cast(previous_purchases as float)),2) AS avg_previous_purchases
FROM retail_cleaned
GROUP BY subscription_status;


-- 8.Top 5 products with highest discount usage %

select * from retail_cleaned;


with discount_usage as(
select category,customer_id,
case when discount_applied='Yes' then 1.0
	else 0.0 end as discount from retail_cleaned)

select category,
round(avg(discount)*100,2) as discount_percent
from discount_usage group by category;

SELECT 
    category,
    ROUND(
        AVG(
            CASE 
                WHEN discount_applied = 'Yes' THEN 1.0
                ELSE 0.0
            END
        ) * 100,
    2) AS discount_percent
FROM retail_cleaned
GROUP BY category;


select top 5 item_purchased,count(item_purchased) as number_of_times_sold,
count(case when discount_applied='Yes' then 1 end) as number_sold_when_discount,
count(case when discount_applied='Yes' then 1 end)*100.0/count(*) as discount_usage_percent
from retail_cleaned group by item_purchased order by discount_usage_percent desc;


--9. Segment customer into new, returning and loyal based on total number of previous purchase
--and show count in each segment.
 SELECT 
    CASE 
        WHEN CAST(previous_purchases AS FLOAT) = 0 THEN 'New Customers'
        WHEN CAST(previous_purchases AS FLOAT) BETWEEN 1 AND 15 THEN 'Returning Customers'
        ELSE 'Loyal Customers'
    END AS customer_segment,

    COUNT(customer_id) AS total_customers

FROM retail_cleaned
GROUP BY 
    CASE 
        WHEN CAST(previous_purchases AS FLOAT) = 0 THEN 'New Customers'
        WHEN CAST(previous_purchases AS FLOAT) BETWEEN 1 AND 15 THEN 'Returning Customers'
        ELSE 'Loyal Customers'
    END;

SELECT 
    COLUMN_NAME,
    DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'retail_cleaned';

-- 10.Are customers who are repeat buyer (more than 5 previous purchases) are likely to subscribe ?

select * from retail_cleaned;

select subscription_status,count(customer_id) as total_customer, ROUND(
        COUNT(customer_id) * 100.0 / SUM(COUNT(customer_id))over(),
    2) AS percentage_share
from retail_cleaned where cast(previous_purchases as float)>5 group by subscription_status;



-- 11. What are top 3 most purchased products within each category
WITH ranked_products AS (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_purchases,
        
        RANK() OVER (
            PARTITION BY category 
            ORDER BY COUNT(*) DESC
        ) AS rnk

    FROM retail_cleaned
    GROUP BY category, item_purchased
)

SELECT 
    category,
    item_purchased,
    total_purchases
FROM ranked_products
WHERE rnk <= 3
ORDER BY category, total_purchases DESC;

-- 12.What is revenue contribution of each age group. 


select * from retail_cleaned;

select case when age between 18 and 25 then '18-25'
			when age between 26 and 35 then '26-35'
			when age between 36 and 50 then '36-50'
			else '51+'
			end as age_group,
		count(customer_id) as total_counts,
		sum(purchase_amount) as total_revenue,
		round(sum(purchase_amount)*100/sum(sum(purchase_amount)) over(),2) as revenue_percent
	from retail_cleaned 
	group by 
	case when age between 18 and 25 then '18-25'
			when age between 26 and 35 then '26-35'
			when age between 36 and 50 then '36-50'
			else '51+' end;

WITH age_data AS (
    SELECT 
        customer_id,
        purchase_amount,
        CASE 
            WHEN age BETWEEN 18 AND 25 THEN '18-25'
            WHEN age BETWEEN 26 AND 35 THEN '26-35'
            WHEN age BETWEEN 36 AND 50 THEN '36-50'
            ELSE '51+'
        END AS age_group
    FROM retail_cleaned
)

SELECT 
    age_group,
    COUNT(customer_id) AS total_customers,
    SUM(purchase_amount) AS total_revenue,

    ROUND(
        SUM(purchase_amount) * 100.0 / SUM(SUM(purchase_amount)) OVER(),
    2) AS revenue_percent

FROM age_data
GROUP BY age_group;